### ISSUE TITLE
compilation error on import

### ISSUE THREAD

**Issue by sreev** [satori-com/satori-rtm-sdk-java#1]
eclipse:
file->import->existing gradle project

shows compilation error:
satori-sdk-java-core/src/integration/java/com.satori.rtm.AbstractRealTest.java

**Comment by satori-avasenin** [comment]
Thank you for report.

We are using Gradle configurations to specify dependencies for our integration tests and looks like Eclipse doesn't work with them correctly due to common `.classpath` for all configurations.

We can't add gson as compile dependency for `core` because code of `core` doesn't depend on gson. Only our integration tests requires gson to parse config.

I'm going to move integration test to another package which should solve your compilation issue for Eclipse.

Thanks,

**Comment by sreev** [comment]
sure. thanks @satori-avasenin.

**Comment by sreev** [comment]
thanks, @mehmetg . looks like the changes that @satori-avasenin suggested above are not in the main branch, still ? do you know when would they be in. would you mind keeping this issue open until then, please. thanks, again.
